#we are creating a connection so that we can access it with our spring boot application

server:
  port: 8080

spring:
  datasource:
    #customer is the database we are going to create
    url: jdbc:postgresql://localhost:5332/customer
    username: melissa
    password: password
  jpa:
    hibernate:
      #saying we want to destroy the schema at the end of the session
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet