#we are creating a connection so that we can access it with our spring boot application

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: melissasantos
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet